### ISSUE TITLE
Tag 2.6.7

### ISSUE THREAD

**Issue by mario-almeida** [philyuchkoff/HAProxy-2-RPM-builder#11]
Please create 2.6.7 tag

**Comment by philyuchkoff** [comment]
Done.
https://github.com/philyuchkoff/HAProxy-2-RPM-builder/releases/tag/2.6.7

**Comment by mario-almeida** [comment]
> Done. https://github.com/philyuchkoff/HAProxy-2-RPM-builder/releases/tag/2.6.7

I think you cloned 2.7 instead of 2.6 as in the Makefile it says 2.7

![image](https://user-images.githubusercontent.com/774032/206713794-617f7c81-fdc3-4a6f-81f0-4bfa45b715f9.png)
