### ISSUE TITLE
Сборка для Amazon Linux 2 не работает

### ISSUE THREAD

**Issue by vkhodor** [philyuchkoff/HAProxy-2-RPM-builder#2]
`make[1]: Leaving directory `/opt/HAProxy-2-RPM-builder/rpmbuild/BUILD/haproxy-2.0.13'
+ exit 0
Выполняется(%install): /bin/sh -e /var/tmp/rpm-tmp.HVpEXK
+ umask 022
+ cd /opt/HAProxy-2-RPM-builder/rpmbuild/BUILD
+ '[' /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64 '!=' / ']'
+ rm -rf /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64
++ dirname /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64
+ mkdir -p /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT
+ mkdir /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64
+ cd haproxy-2.0.13
+ '[' /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64 '!=' / ']'
+ /usr/bin/rm -rf /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/usr/sbin
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/haproxy
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/haproxy/errors
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/usr/share/man/man1/
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/logrotate.d
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/rsyslog.d
+ /usr/bin/install -d /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/var/log/haproxy
+ /usr/bin/install -s haproxy /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/usr/sbin/
+ /usr/bin/install -c -m 644 /opt/HAProxy-2-RPM-builder/rpmbuild/SOURCES/haproxy.cfg /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/haproxy/haproxy.cfg
+ /usr/bin/install -c -m 755 examples/errorfiles/400.http examples/errorfiles/403.http examples/errorfiles/408.http examples/errorfiles/500.http examples/errorfiles/502.http examples/errorfiles/503.http examples/errorfiles/504.http /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/haproxy/errors/
+ /usr/bin/install -c -m 755 doc/haproxy.1 /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/usr/share/man/man1/
+ /usr/bin/install -c -m 755 /opt/HAProxy-2-RPM-builder/rpmbuild/SOURCES/haproxy.syslog.amzn2 /opt/HAProxy-2-RPM-builder/rpmbuild/BUILDROOT/haproxy-2.0.13-1.x86_64/etc/rsyslog.d/49-haproxy.conf
/usr/bin/install: cannot stat '/opt/HAProxy-2-RPM-builder/rpmbuild/SOURCES/haproxy.syslog.amzn2': No such file or directory
ошибка: Неверный код возврата из /var/tmp/rpm-tmp.HVpEXK (%install)

Ошибки сборки пакетов:
    Неверный код возврата из /var/tmp/rpm-tmp.HVpEXK (%install)
make: *** [build] Ошибка 1
`

**Comment by philyuchkoff** [comment]
Виктор, попробуйте сейчас?

**Comment by vkhodor** [comment]
Все работает! Круто! Большое спасибо!
