### ISSUE TITLE
Rpm wiht LUA and PROMEX

### ISSUE THREAD

**Issue by npoojary** [philyuchkoff/HAProxy-2-RPM-builder#26]
We need to build rpm to work with LUA and PROMEX. Would be helpful if you update the code to build with both the features. Thanks.

**Comment by npoojary** [comment]
I am able to build rpm by setting USE_PROMETHEUS?=1 in Makefile and  sudo make USE_LUA=1

**Comment by philyuchkoff** [comment]
you can build with:
`sudo make USE_LUA=1 USE_PROMETHEUS=1`

then, check:
`haproxy -vvv`

you have to see:
`...`
`Built with Lua version : Lua 5.4.4`
`...`
`Built with the Prometheus exporter as a service`
`...`

![Снимок экрана 2024-02-02 в 19 36 25](https://github.com/philyuchkoff/HAProxy-2-RPM-builder/assets/6699359/276c4182-9a9f-439f-b281-7dabcee16744)
