### ISSUE TITLE
[ALERT] 093/083850 (73356) : Starting frontend GLOBAL: cannot bind UNIX socket [/var/lib/haproxy/stats]

### ISSUE THREAD

**Issue by koperait** [philyuchkoff/HAProxy-2-RPM-builder#3]
после установки пакета на Centos 7 не стартует и в journalctl -xe ругается [ALERT] 093/083850 (73356) : Starting frontend GLOBAL: cannot bind UNIX socket [/var/lib/haproxy/stats]
решается просто # mkdir /var/lib/haproxy/ и тогда все взлетает на ура.

Спасибо Вам за ваш труд!

**Comment by philyuchkoff** [comment]
Спасибо!
